
[build]
  publish = "dist" # Assuming your build output directory is 'dist'
  command = "npm run build && cp -r server/public/audio dist/"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/audio/*"
  to = "/audio/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/audio/*"
  [headers.values]
    Content-Type = "audio/mpeg"
    Cache-Control = "public, max-age=31536000"